#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cryptolet.Droid.Resource", IsApplication=true)]

namespace Cryptolet.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F02000A
			public const int all_tab = 2130837514;
			
			// aapt resource value: 0x7F020000
			public const int BCH = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int BTC = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int DASH = 2130837506;
			
			// aapt resource value: 0x7F02000B
			public const int deposited = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int deposited_tab = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int emptyview = 2130837517;
			
			// aapt resource value: 0x7F020003
			public const int EOS = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ETH = 2130837508;
			
			// aapt resource value: 0x7F02000E
			public const int grow = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int icon_about = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int icon_feed = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int login = 2130837521;
			
			// aapt resource value: 0x7F020005
			public const int LTC = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int NEO = 2130837510;
			
			// aapt resource value: 0x7F020012
			public const int nice = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int register = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int security = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int welcome = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int withdrawn = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int withdrawn_tab = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int xamarin_logo = 2130837528;
			
			// aapt resource value: 0x7F020007
			public const int XLM = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int XMR = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int XRP = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
